# Generated by Django 3.2.5 on 2021-10-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_rename_ignore_user_ignoreuser_ignored_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['id'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='commentaries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=55, unique=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='country',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='countries', verbose_name='Флаг'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_user.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='ignoreuser',
            name='ignored_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignore_user', to='custom_user.customuser'),
        ),
        migrations.AlterField(
            model_name='ignoreuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='custom_user.customuser'),
        ),
        migrations.AlterUniqueTogether(
            name='ignoreuser',
            unique_together={('user', 'ignored_user')},
        ),
    ]
