# Generated by Django 3.2.5 on 2021-07-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_errormodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorModel',
        ),
    ]
