# Generated by Django 3.2.5 on 2021-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_delete_errormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
