# Generated by Django 3.2.5 on 2021-07-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_theme_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='popularity',
        ),
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
