version: "3"

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5431:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=admin

  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./static/:/static
    ports:
      - "80:80"
    depends_on:
      - django
      - postgres

  redis:
    image:redis
